### PR TITLE
Small update

### PR DESCRIPTION
**Pull request by mtancoigne**
Added usage in readme and an info about dev libs, changed the usage string in app, and added a "cmake_minimum_required" line in CMakeLists.txt

### CODE REVIEW

**Comment by vishesh** [comment]
Thanks for contributing.

In README.md:25, the command is applicable only for Debian and its derivatives or distros using apt-get. IMO it 's better to say that kdelibs development package is required. The the name of package is kdelibs-dev in distro X.

Also, why kdelibs5?

**Comment by mtancoigne** [comment]
hu, because that was the first libs i found on my system (ubuntu 13.04) that worked. I know previous versions might do the same job, but I didn't tried them (same for `cmake_minimum_version` in CMakeLists.txt).

For the apt-get line, I understand that it's a distro-specific package manager, but sudo is not installed by default on each distro too :)

**Comment by vishesh** [comment]
If it can work on a lower minimum version, we should probably use that.

I still don't understand why are you unwilling to mention package name
rather than the command. I'm pretty sure that the person who will use this
utility will figure out how to install it.

**Comment by mtancoigne** [comment]
Well, I guess I can close this now :)

**Pull request closed without merging**
